# Imports

In [2]:
import pandas as pd
import sqlite3

In [3]:
RawData = pd.read_csv(r'Data Raw/ObsList.csv')
TaxonomyData = pd.read_csv(r'Data Raw/TaxonomyRaw.csv')
Regions = pd.read_csv(r'Data Raw/RegionsTableData.csv', sep=';')
Natives = pd.read_csv(r'Data Raw/NativeRaw.csv', sep=';')

In [4]:
RawData.head(5)

,Species,Area,Realm,Cryptogenic,Introduced,Dispersal,Established,Eradicated,Intentional_Release,Year,Reference Year,Reference
0,Spodoptera eridania,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
1,Phyllocnistis citrella,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
2,Hypsipyla grandella,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
3,Spodoptera eridania,United States,Nearctic,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
4,Hyphantria cunea,United States,Nearctic,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...

In [5]:
TaxonomyData.head(5)

,Species,AcceptedSpecies,Genus,Family
0,Spodoptera eridania,Spodoptera eridania,Spodoptera,Noctuidae
1,Phyllocnistis citrella,Phyllocnistis citrella,Phyllocnistis,Gracillariidae
2,Hypsipyla grandella,Hypsipyla grandella,Hypsipyla,Pyralidae
3,Hyphantria cunea,Hyphantria cunea,Hyphantria,Erebidae
4,Phthorimaea operculella,Phthorimaea operculella,Phthorimaea,Gelechiidae

In [6]:
Regions.head(5)

    AreaID              AreaName               Country Continent SubContinent
0  AFG.1_1           Afghanistan           Afghanistan      Asia          NaN
1  AGO.1_1                Angola                Angola    Africa          NaN
2  ALB.1_1               Albania               Albania    Europe          NaN
3  AND.1_1               Andorra               Andorra    Europe          NaN
4  ARE.1_1  United Arab Emirates  United Arab Emirates      Asia          NaN

In [7]:
Natives.head(5)

,Species,AcceptedSpecies,Continent,Cosmopolitan,Reference Year,Reference
0,Artigisa melanephele,Artigisa melanephele,Australia,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
1,Acrocercops laciniella,Acrocercops laciniella,Australia,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
2,Bleszynskia malacelloides,Bleszynskia malacelloides,Australia,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
3,Zomariana doxasticana,Zomariana doxasticana,Australia,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
4,Stegommata leptomitella,Stegommata leptomitella,Australia,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."

# Taxonomy

In [8]:
TaxonomyData['SpeciesID'] = 'SP' + (TaxonomyData.index +1).astype(str)

In [9]:
TaxonomyData

,Species,AcceptedSpecies,Genus,Family,SpeciesID
0,Spodoptera eridania,Spodoptera eridania,Spodoptera,Noctuidae,SP1
1,Phyllocnistis citrella,Phyllocnistis citrella,Phyllocnistis,Gracillariidae,SP2
2,Hypsipyla grandella,Hypsipyla grandella,Hypsipyla,Pyralidae,SP3
3,Hyphantria cunea,Hyphantria cunea,Hyphantria,Erebidae,SP4
4,Phthorimaea operculella,Phthorimaea operculella,Phthorimaea,Gelechiidae,SP5
...,...,...,...,...,...
1611,Oegoconia quadripuncta,Oegoconia quadripuncta,Oegoconia,Autostichidae,SP1612
1612,Arcola malloi,Arcola malloi,Arcola,Pyralidae,SP1613
1613,Cactoblastis doddi,Cactoblastis doddi,Cactoblastis,Pyralidae,SP1614
1614,Manoba brunellus,Manoba brunellus,Manoba,Nolidae,SP1615
1615,Zophodia convolutella,Zophodia convolutella,Zophodia,Pyralidae,SP1616

# References

In [10]:
ReferencesObs = RawData[['Reference Year', 'Reference']].copy()
ReferencesObs.drop_duplicates(inplace=True)
ReferencesObs.reset_index(drop=True, inplace=True)

In [11]:
ReferencesObs.head(5)

   Reference Year                                          Reference
0            2024  CAB International (CABI) (2024). CABI Invasive...
1            2020  Gilligan, T., Brown, J. and Baixeras, J. (2020...
2            2024  European and Mediterranean Plant Protection Or...
3            2009  Fodor, E. and Haruta, O. (2009). Niche partiti...
4            2010  Heard, T., Elliott, L., Anderson, B., White, L...

In [12]:
ReferencesNat = Natives[['Reference Year', 'Reference']].copy()
ReferencesNat.drop_duplicates(inplace=True)
ReferencesNat.reset_index(drop=True, inplace=True)

In [13]:
ReferencesNat

     Reference Year                                          Reference
0              2001  Hoare, R. (2001). Adventive species of Lepidop...
1              2015  Yamanaka, T., Morimoto, N., Nishida, G., Kirit...
2              1992  Frank, J. and McCoy, E. (1992). Introduction t...
3              2017  Dawidowicz, L. and Rozwalka, R. (2017). Anatra...
4              2010  Lopez-Vaamonde, C., Agassiz, D., Augustin, S.,...
..              ...                                                ...
740            2024  Witts, H. (2024). Hypsopygia nostralis (Guenée...
741            2005  De Prins, W. (2005). Oegoconia caradjai, a new...
742            2001  Mariau, D. (2001). The fauna of oil palm and c...
743            2008  Hao, S. (2008). New Recorded Species of Pterop...
744            2011  Tennent, J. (2011). Pontia daplidice. The IUCN...

[745 rows x 2 columns]

In [14]:
References = pd.concat([ReferencesObs, ReferencesNat]).drop_duplicates().reset_index(drop=True)

In [15]:
References['ReferenceID'] = 'REF' + (References.index +1).astype(str)

In [16]:
References

,Reference Year,Reference,ReferenceID
0,2024,CAB International (CABI) (2024). CABI Invasive...,REF1
1,2020,"Gilligan, T., Brown, J. and Baixeras, J. (2020...",REF2
2,2024,European and Mediterranean Plant Protection Or...,REF3
3,2009,"Fodor, E. and Haruta, O. (2009). Niche partiti...",REF4
4,2010,"Heard, T., Elliott, L., Anderson, B., White, L...",REF5
...,...,...,...
1119,2024,"Sterling, M., Barclay, M. and Lees, D. (2024)....",REF1120
1120,2005,"De Prins, W. (2005). Oegoconia caradjai, a new...",REF1121
1121,2001,"Mariau, D. (2001). The fauna of oil palm and c...",REF1122
1122,2008,"Hao, S. (2008). New Recorded Species of Pterop...",REF1123
1123,2011,"Tennent, J. (2011). Pontia daplidice. The IUCN...",REF1124

# Realms

In [ ]:
Realm =