# Imports

In [1]:
import pandas as pd
import sqlite3

In [2]:
RawData = pd.read_csv(r'Data Raw/ObsList.csv')
TaxonomyData = pd.read_csv(r'Data Raw/TaxonomyRaw.csv')
Regions = pd.read_csv(r'Data Raw/RegionsTableData.csv', sep=';')
Natives = pd.read_csv(r'Data Raw/NativeRaw.csv', sep=';')

In [3]:
RawData.head(5)

,Species,Area,Realm,Cryptogenic,Introduced,Dispersal,Established,Eradicated,Intentional_Release,Year,Reference Year,Reference
0,Spodoptera eridania,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
1,Phyllocnistis citrella,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
2,Hypsipyla grandella,Brazil,Neotropical,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
3,Spodoptera eridania,United States,Nearctic,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...
4,Hyphantria cunea,United States,Nearctic,NaN,NaN,NaN,1.0,0.0,NaN,NaN,2024,CAB International (CABI) (2024). CABI Invasive...

In [4]:
TaxonomyData.head(5)

,Species,AcceptedSpecies,Genus,Family
0,Spodoptera eridania,Spodoptera eridania,Spodoptera,Noctuidae
1,Phyllocnistis citrella,Phyllocnistis citrella,Phyllocnistis,Gracillariidae
2,Hypsipyla grandella,Hypsipyla grandella,Hypsipyla,Pyralidae
3,Hyphantria cunea,Hyphantria cunea,Hyphantria,Erebidae
4,Phthorimaea operculella,Phthorimaea operculella,Phthorimaea,Gelechiidae

In [5]:
Regions.head(5)

    AreaID              AreaName               Country Continent SubContinent
0  AFG.1_1           Afghanistan           Afghanistan      Asia          NaN
1  AGO.1_1                Angola                Angola    Africa          NaN
2  ALB.1_1               Albania               Albania    Europe          NaN
3  AND.1_1               Andorra               Andorra    Europe          NaN
4  ARE.1_1  United Arab Emirates  United Arab Emirates      Asia          NaN

In [6]:
Natives.head(5)

,Species,AcceptedSpecies,Continent,Realm,Cosmopolitan,Reference Year,Reference
0,Bleszynskia malacelloides,Bleszynskia malacelloides,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
1,Artigisa melanephele,Artigisa melanephele,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
2,Acrocercops laciniella,Acrocercops laciniella,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
3,Zomariana doxasticana,Zomariana doxasticana,Australia,Australian,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."
4,Coleophora striatipennella,Coleophora striatipennella,Europe,Palearctic,0,2001,"Hoare, R. (2001). Adventive species of Lepidop..."

# [1] Base Tables Updates

Besides the Areas (Geographical Regions) base table there were no tables fully udpdated on the database, so we started by separating the data that was fully merged on the observation table onto separate parts. Composing: Taxonomy, Realms and References.

## [1.1] Taxonomy

In [40]:
TaxonomyData['SpeciesID'] = 'SP' + (TaxonomyData.index +1).astype(str)

In [41]:
TaxonomyData

,Species,AcceptedSpecies,Genus,Family,SpeciesID
0,Spodoptera eridania,Spodoptera eridania,Spodoptera,Noctuidae,SP1
1,Phyllocnistis citrella,Phyllocnistis citrella,Phyllocnistis,Gracillariidae,SP2
2,Hypsipyla grandella,Hypsipyla grandella,Hypsipyla,Pyralidae,SP3
3,Hyphantria cunea,Hyphantria cunea,Hyphantria,Erebidae,SP4
4,Phthorimaea operculella,Phthorimaea operculella,Phthorimaea,Gelechiidae,SP5
...,...,...,...,...,...
1611,Oegoconia quadripuncta,Oegoconia quadripuncta,Oegoconia,Autostichidae,SP1612
1612,Arcola malloi,Arcola malloi,Arcola,Pyralidae,SP1613
1613,Cactoblastis doddi,Cactoblastis doddi,Cactoblastis,Pyralidae,SP1614
1614,Manoba brunellus,Manoba brunellus,Manoba,Nolidae,SP1615
1615,Zophodia convolutella,Zophodia convolutella,Zophodia,Pyralidae,SP1616

## [1.2] Realms

## [1.3] References

In [42]:
ReferencesObs = RawData[['Reference Year', 'Reference']].copy()
ReferencesObs.drop_duplicates(inplace=True)
ReferencesObs.reset_index(drop=True, inplace=True)

In [43]:
ReferencesObs.head(5)

   Reference Year                                          Reference
0            2024  CAB International (CABI) (2024). CABI Invasive...
1            2020  Gilligan, T., Brown, J. and Baixeras, J. (2020...
2            2024  European and Mediterranean Plant Protection Or...
3            2009  Fodor, E. and Haruta, O. (2009). Niche partiti...
4            2010  Heard, T., Elliott, L., Anderson, B., White, L...

In [44]:
ReferencesNat = Natives[['Reference Year', 'Reference']].copy()
ReferencesNat.drop_duplicates(inplace=True)
ReferencesNat.reset_index(drop=True, inplace=True)

In [45]:
ReferencesNat

     Reference Year                                          Reference
0              2001  Hoare, R. (2001). Adventive species of Lepidop...
1              1992  Frank, J. and McCoy, E. (1992). Introduction t...
2              2010  Lopez-Vaamonde, C., Agassiz, D., Augustin, S.,...
3              2020  Gilligan, T., Brown, J. and Baixeras, J. (2020...
4              2022  Calhoun, J. and Smith, R. (2022). Brephidium e...
..              ...                                                ...
720            1960  Gozmany L. (1960). The results of the zoologic...
721            2017  Cock, M. (2017) A preliminary catalogue of the...
722            1987  Diakonoff, A. and van Nieukerken, E. (1987). E...
723            2003  Baran, T. (2003). Scythris buszkoi sp. n., a n...
724            2017  Dawidowicz, L. and Rozwalka, R. (2017). Anatra...

[725 rows x 2 columns]

In [46]:
References = pd.concat([ReferencesObs, ReferencesNat]).drop_duplicates().reset_index(drop=True)

In [47]:
References['ReferenceID'] = 'REF' + (References.index +1).astype(str)

In [48]:
References

,Reference Year,Reference,ReferenceID
0,2024,CAB International (CABI) (2024). CABI Invasive...,REF1
1,2020,"Gilligan, T., Brown, J. and Baixeras, J. (2020...",REF2
2,2024,European and Mediterranean Plant Protection Or...,REF3
3,2009,"Fodor, E. and Haruta, O. (2009). Niche partiti...",REF4
4,2010,"Heard, T., Elliott, L., Anderson, B., White, L...",REF5
...,...,...,...
1100,2023,"Assaad, M. (2023). Ecology and impacts of inse...",REF1101
1101,1960,Gozmany L. (1960). The results of the zoologic...,REF1102
1102,2017,"Cock, M. (2017) A preliminary catalogue of the...",REF1103
1103,1987,"Diakonoff, A. and van Nieukerken, E. (1987). E...",REF1104
1104,2003,"Baran, T. (2003). Scythris buszkoi sp. n., a n...",REF1105

In [49]:
RealmObs = RawData[['Realm']].copy()
RealmNat = Natives[['Realm']].copy()

Realms = pd.concat([RealmObs, RealmNat]).drop_duplicates().reset_index(drop=True)
Realms['RealmID'] = 'RLM' + (Realms.index +1).astype(str)

In [50]:
Realms

             Realm RealmID
0      Neotropical    RLM1
1         Nearctic    RLM2
2         Oceanina    RLM3
3         Oriental    RLM4
4    Sino-Japanese    RLM5
5     Afrotropical    RLM6
6       Palearctic    RLM7
7       Australian    RLM8
8       Panamanian    RLM9
9   Saharo-Arabian   RLM10
10      Madagascan   RLM11